### ISSUE TITLE
Create new directory for POSV consensus

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#114]
Currently, we are still working on `clique` directory to implement POSV consensus.

From my point of view, we should create new directory for POSV consensus before releasing the first version.

And we also need to custom the log below:
```
INFO [08-07|02:38:37] Initialised chain configuration          config="{ChainID: 89 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: clique}"
```

**Comment by ngtuna** [comment]
closed via #125
