### ISSUE TITLE
Suggest to custom consensus for testnet

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#158]
The node run in testnet should use params `--testnet`
In testnet, We have 150 masternode, but only have 3 block producers, the others masternodes are signers. Block Producers are nodes that have highest stake. We use same reward engine for both testnet and mainnet

This will be help us to keep testnet stable, even there are alot of candidates come and leave, candidates who want to try tomochain testnet.

This customization  should release in 0.1.1 version.

**Comment by Logle** [comment]
Two approaches 1) testnet to be used as a test version for the mainnet; 2) permanent testnet for writing/ running smart-contracts. These are two different things. If we focus on 1), the specs should be as close as the mainnet as possible (at least for sometimes). There will be many reviewers in the next few months, and we don't want confusion.

**Comment by ngtuna** [comment]
So if we go with 1), we must have clear and tight requirements for running a masternode to ensure that people don't play trick on us. I will hold this feature until we want to roll out the option 2). Remove it out of the 0.2.0 release for now.

**Comment by ngtuna** [comment]
Testnet now running with 3 MNs only create blocks. Other MNs still can validate and get reward. Good to close this issue now
