### ISSUE TITLE
Chain stops after import over 300K blocks

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#159]
I tried to setup a full-node connect to 3 bootnodes on testnet. It work ok until block number 345596
See logs file below:
[test.zip](https://github.com/tomochain/tomochain/files/2331324/test.zip)

Use tool https://github.com/tomochain/masternode

**Comment by thanhson1085** [comment]
Test again. stops at 350996

[test3.zip](https://github.com/tomochain/tomochain/files/2334427/test3.zip)

**Comment by ngtuna** [comment]
I'll take this. We should fix and roll out 0.1.1 for this

**Comment by thanhson1085** [comment]
It is quite clear now, we need to open port 30303 for full node

**Comment by thanhson1085** [comment]
It is not easy to detect the cause. full-node arbitrary stop event opening port 30303 or not

**Comment by thanhson1085** [comment]
Log for open port 30303, but still stop import
[chain.zip](https://github.com/tomochain/tomochain/files/2335001/chain.zip)

**Comment by ngtuna** [comment]
fix via #164

**Comment by ngtuna** [comment]
It's been testing on our devnet and it seems to work very well. So I am going to close this. Please feel free to reopen it if something doens't work as expected.
