### ISSUE TITLE
Simple slashing to the game

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#182]
We have been thinking about slashing for a while. The idea is not trying to blame unstable masternodes but maintaining a stable network. Right now if one masternode fails to produce a block on his turn, network will be delayed in 12 seconds (2 seconds of block-time and 10 seconds timeout). A worse case: when a masternode doesn't get involved in any block within epoch, of course he won't receive any reward (neither his voters) but network will be affected by not only some delaying but reducing the probability of block finality. Definitely we don't encourage that. On the other side, a big advantage of POSV consensus is mostly removing double spending attack in the system. Thus, we are currently trying to mitigate the first case. Ideas will come by more research.

For now, we want to inject a simple slashing to the system as below:

- there will be a ticker injected in the system to calculate how many blocks one masternode has validated within an epoch.
- If one masternode is silence during an epoch, he will be kicked out of the list by the next 4 epochs. During this period, the 151th candidate will be automatically promoted to replace his seat.
- At the 5th epoch, that masternode has change to go back to the list. Of couse he has to fight with the others by the total token locked for him (deposit + vote)

**Comment by ngtuna** [comment]
Some adjustments after discussion today:

- The kicked masternode can still verify blocks within the slashed period (4 epochs). We use this allowance to notice when he's online back.
- He receives permission to come back to the list at epoch 5. There is no candidate will be taking his slot.

**Comment by ngtuna** [comment]
Need to solve this below case as well:

- two MNs running with the same registered candidate account.

**Comment by ngtuna** [comment]
> Need to solve this below case as well:
two MNs running with the same registered candidate account.

This case will be mitigated separately at this #191

**Comment by phamvancam2104** [comment]
4 epochs after being kicked out of the masternode list, does the kicked masternode still remain its  masternode position, even if it is not in the top 150 most voted candidates?

**Comment by ngtuna** [comment]
closed via #212
