### ISSUE TITLE
Testnet stops frequently

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#186]
At the moment, We have 9 masternodes, includes 1 masternode stoped.

three recent days, Testnet stops 6 times.

When testnet stops, just restart 3 masternodes (Sun, Moon, Earth), it is back to works. 

Need to investigate the root issue and fix it ASAP.

**Comment by ngtuna** [comment]
So the root issue might come from two MNs running under the same account which causes chain forked and waiting gap between MNs now is a bit short (2s). We take the first action on this issue by this PR #187. Further discussion will be around how to detect the duplicated account case described above and how to react on that.

**Comment by ngtuna** [comment]
We can close this issue via PR #202
