### ISSUE TITLE
rebase strategy

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#19]
It's worth to keep updated to upstream go-ethereum for interesting features. We need to define a good strategy for rebasing.

**Comment by benjiqq** [comment]
what about other incompatible changes to the core - e.g. does tomo include uncle mining? could be removed afaics. ETH is a stable protocol (minus the PoS switch), so I think tomo has the opportunity to make breaking improvements which ETH can not do.

**Comment by ngtuna** [comment]
Oops sorry I missed this one. I will shift this discussion to #51 and close this one
