### ISSUE TITLE
Pkey should be deleted from container once the account has been imported

### ISSUE THREAD

**Issue by etienne-napoleone** [BuildOnViction/tomochain-v1#193]
The pkey has to be a file to be imported as an account by tomo.

Currently, we create a file but doesn't delete it:
https://github.com/tomochain/tomochain/blob/e20d9797fff6af3d655bd648f53c2c2bd7a74959/docker/tomochain/entrypoint.sh#L96

We should either:
- use shell capabilites of using stdout as a file like `cat <(echo $pkey)` to avoid using a file. It might not be possible with the `sh` shell
- or delete the file afterward

**Comment by ngtuna** [comment]
👍
