### ISSUE TITLE
Masternode sends its seed to smart contract at end of epoch

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#21]
All masternode need to send its seed (list of random numbers) to the smart contract before the epoch ends. Recommended block number: 900

**Comment by benjiqq** [comment]
which contract is that? step1 here defines array _Recommend_ at the beginning of epoch
https://docs.tomochain.com/whitepaper/#random-matrix-and-smart-contract

**Comment by thanhson1085** [comment]
Will public randomize smart contract it early next week.

**Comment by ngtuna** [comment]
fixed via #153
