### ISSUE TITLE
genesis block mismatch on node restart

### ISSUE THREAD

**Issue by etienne-napoleone** [BuildOnViction/tomochain-v1#221]
docker image: `tomochain/node:439464713`
commit: 72992136e2c1e3dcd64c29b95c4db5a10c7f9443

after restarting node moon in devnet (data was not deleted or changed), node can't sync because of genesis block mismatch.

```
DEBUG[10-16|10:23:08] Removing p2p peer                        id=6498849e2002f999 conn=dyndial duration=933.47µs  peers=2 req=false err="Genesis block mismatch - 263dc4ead000c220 (!= 08c8d4366623d91f)"
```

Tried multiple restarting without success. Deleting the data and restarting worked.

**Comment by ngtuna** [comment]
relevant issue #184

**Comment by ngtuna** [comment]
close as dup
