### ISSUE TITLE
Debugging message as INFO

### ISSUE THREAD

**Issue by etienne-napoleone** [BuildOnViction/tomochain-v1#229]
```
INFO [10-23|08:02:16] Debugging len(masternodes)=3 number=15 limit=2 seen=14 recent=0xf99805B536609cC03AcBB2604dFaC11E9E54a448 snap.Recents="map[13:[49 178 73 254 111 38 122 162 57 110 178 220 54 233 199 147 81 217 126 197] 14:[249 152 5 181 54 96 156 192 58 203 178 96 77 250 193 30 158 84 164 72]]"
```

**Comment by ngtuna** [comment]
can you also take this @etienne-napoleone ?

**Comment by Meabo** [comment]
Hello, I'd like to help but you can detail the issue please ?

**Comment by etienne-napoleone** [comment]
Hello @Meabo ! 
The problem here is that this log message with debug info is logged at info level. Is this still relevant @ngtuna ?

**Comment by ngtuna** [comment]
Yes still. PR's welcome. Might be better to scan through log messages to correct some more

**Comment by ngtuna** [comment]
solved at https://github.com/tomochain/tomochain/commit/e94daa8#diff-4c5ceab88fd21ba8bb6636813782d849L919
