### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#29]

**Comment by benjiqq** [comment]
- license information
- build information

**Comment by benjiqq** [comment]
* basic intro to PoA and PoS, as well as links to build info or test-net and governance app could be helpful

**Comment by ngtuna** [comment]
@benjyz It's coming soon sorry for those missing bits. We are under heavy development atm. For the basic intro of PoA and PoS, PR is welcome.

**Comment by benjiqq** [comment]
@ngtuna sure np, thanks for this work. created separate issue for license
https://github.com/tomochain/tomochain/issues/36

**Comment by ngtuna** [comment]
closed via #151
