### ISSUE TITLE
how to connect to the mainnet

### ISSUE THREAD

**Issue by bitcodernull** [BuildOnViction/tomochain-v1#347]
i want to connect the mainnet, but i have got the following info, and the node can not sync the data:

DEBUG[12-17|09:12:45] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:12:50] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:12:55] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:00] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:05] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:10] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:15] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:20] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:25] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:30] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:35] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:40] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:45] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:50] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s
DEBUG[12-17|09:13:55] Recalculated downloader QoS values       rtt=5s confidence=1.000 ttl=5s

maybe my configuration is not correct, or miss some important configuration
where i can get the document about how to connect to the mainnet

**Comment by etienne-napoleone** [comment]
Hello @bitcodernull,
You can find the documentation on running a node in mainnet on our [documentation website](https://docs.tomochain.com/masternode/requirements/).
If you have any questions, feel free to drop by our [gitter channel](https://gitter.im/tomochain/tomochain). 
cheers!
