### ISSUE TITLE
Wake testnet up

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#351]
After mainnet, a lot nodes in testnet shutdown without resigning. So the testnet run slowly now, we need wake it up.
We will reset Testnet, and run a new Testnet network (fast, stable, secure, decentralize)

TomoChain Testnet:
- add tag `--testnet`
- custom POSV concensus: select top 3 nodes to become Block Producer nodes

**Comment by dinhln89** [comment]
https://github.com/tomochain/tomochain/pull/343

Check it out. Please!

**Comment by ngtuna** [comment]
Closed via #343
