### ISSUE TITLE
License

### ISSUE THREAD

**Issue by benjiqq** [BuildOnViction/tomochain-v1#36]
go-ethereum is published under GPL v3 https://www.gnu.org/licenses/gpl-3.0.en.html

as a side-note go-eth is GPLv3 which requires copies to state modifications if I understand correctly,  see section 5.

**Comment by thanhson1085** [comment]
go-ethereum is published under 2 licenses, GPL for `cmd` directory and LGPL for the others https://github.com/ethereum/go-ethereum#license

**Comment by ngtuna** [comment]
fixed via #97
