### ISSUE TITLE
Cut down chaindata size

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#364]
The way chaindata size grows is urgent. Let's find a good way to slow down the acceleration

**Comment by ngtuna** [comment]
High-level solution explained: https://medium.com/tomochain/chain-data-growth-issue-and-solutions-6d0fb395b085

**Comment by ngtuna** [comment]
mitigate partly via #369

**Comment by gussulliman** [comment]
Thought: 
- Can we store only states and balances? 
* Able to achieve verified computing results that give 
a. merkle path 
b. zero knowledge proof 
* Apply same logic to on chain
* This means only need full merkle and current ZK proof needed at any given time

Block = proof of txs in it 
S1 (state 1) + B1 (block 1) = S2 
B1 = state transition 
State transition can be represented as ZK proof. (zk snark) 

Have check point (epoch? or n epochs in the past?) where state transitions are no longer represented with block, but with the ZK proof and full merkle. 

Can keep all state transitions and merkles, or just keep most recent ZK proof and merkle.

**Comment by ngtuna** [comment]
@gussulliman thanks for the suggestion. It's ambitious design at this moment. I am not sure if there is any blockchain platform provides that storage solution but ZK proof fwics is still at early stage and under heavy research. Can you give a hint on one current blockchain doing that way ? From our side we have planned to cut down the chaindata growth by implementing #369 All achievements have already explained on Long's article

**Comment by ngtuna** [comment]
Closed via #369
