### ISSUE TITLE
eth.getReward(EPOCH_NUMBER) via RPC

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#366]
When client want to getReward for a epoch, just call:
`eth.getReward(EPOCH_NUMBER)` or `eth.getReward(CHECKPOINT_NUMBER)`

**Comment by thanhson1085** [comment]
For persistence, we should provide a option e.g: `--store-reward`
If enable `--store-reward`, node will store reward data to file or db
If not, eth.getReward will return empty

**Comment by thanhson1085** [comment]
Finnaly, the implementation:
`eth.getRewardByHash("BLOCK_HASH")`

**Comment by ngtuna** [comment]
fixed via #367
