### ISSUE TITLE
Run HookReward twice at checkpoint

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#376]
If `--announce-txs` = true, run duplicate HookReward

```
Time Calculated HookReward  block 212400 time 3.545s
Time Calculated HookReward  block 212400 time 3.508s
Time Calculated HookReward  block 213300 time 2.698s
Time Calculated HookReward  block 213300 time 2.731s
```

**Comment by ngtuna** [comment]
fixed via #380

**Comment by thanhson1085** [comment]
Reopen #389

**Comment by thanhnguyennguyen** [comment]
As my investigation, HookPenalty and HookReward are duplicated on the masternodes that create checkpoint blocks: 
- one when they mine new checkpoint blocks
- one when they receive those blocks from M2

**Comment by ngtuna** [comment]
I'm going to close this issue as @thanhnguyennguyen reported
