### ISSUE TITLE
move miner to staking settings

### ISSUE THREAD

**Issue by benjiqq** [BuildOnViction/tomochain-v1#39]
- [x] replace mining with staking see #40 
- [ ] more mining terms
- [ ] change command line interface with proper interface
- [ ] thread setting. staking on several threads is probably not needed?

**Comment by ngtuna** [comment]
#40 was merged. Another PR for updating the CLI is welcome :-)

**Comment by ngtuna** [comment]
@benjyz Are you still interested to keep moving on this issue ?

**Comment by ngtuna** [comment]
related to #41

**Comment by ngtuna** [comment]
I will close this one as we're doing it in our refactored code
