### ISSUE TITLE
Set default gas price economically 

### ISSUE THREAD

**Issue by Logle** [BuildOnViction/tomochain-v1#405]
**Context/ Problem:** 
- TomoChain has a default gas limit per block of 84,000,000 which can theoretically allows for more than 1000 TPS.
- During the recent spam attack, the chain produces around 15GB data per day when the the gas spending hit the limit.
- Gas price should be used as a mechanism to regulate the uses of the resources such as MN's computation and storage. MNs should be compensated in fees for the uses of the network's resources.
**Proposal:**
- Increase the default gas price = 0.25 Gwei. When the gas spending limit is hit, one block will have 0.25 Gwei * 84,000,000 = 21 Finney TOMO or 0.021 TOMO. One epoch fee reward = 0.021 * 900 = 18.9 TOMO.
- This default gas price = 1/4 the most common default gas price in Ethereum (=1 Gwei). Currently TOMO is only 0.25 USD while Ether = 100 USD. That makes the actual cost of TOMO tx fee less than 1/1000 of Ethereum tx fee. 
- With this gas price, 1 tx costs: 0.25 * 21000 (gas limit) = 5,250 Gwei TOMO (1 TOMO can be used for > 190,000 transactions). Tx fee will still be very cheap even when 1TOMO = 1000$. 
- Reference https://www.sitepoint.com/ethereum-transaction-costs

**Comment by ngtuna** [comment]
Minimum gas price default set to 0.25 Gwei will be applied to requests come into TomoChain's RPC endpoint. Masternodes using `tmn` will also set it to 0.25 Gwei. Other masternodes can manually adjust this number on their own RPC endpoint if they want to do via setting the `--gasprice` flag.
