### ISSUE TITLE
remove reference to pow mining

### ISSUE THREAD

**Issue by benjiqq** [BuildOnViction/tomochain-v1#41]
it would be better to factor out pow mining and terms associated with it

- package miner
- command line

see #40

**Comment by ngtuna** [comment]
Agree. Eventually we have to reconstruct the whole project. As tomochain is originally a fork of geth, it is reusing all terms and package architecture.

**Comment by ngtuna** [comment]
@nguyenbatam We should clean up all things related to `mining` and `geth`. Can you work on this ?

**Comment by nguyenbatam** [comment]
Yes,I can

**Comment by ngtuna** [comment]
So we need few more code changes in our cmd/tomo/ package to get rid of POW mining confusion @nguyenbatam

**Comment by ngtuna** [comment]
I will take this

**Comment by ngtuna** [comment]
closed via #197
