### ISSUE TITLE
[Masternode] Run node on mounted space

### ISSUE THREAD

**Issue by tphanson** [BuildOnViction/tomochain-v1#414]
Hey tomo, I tried to run master node on main net and it seems a huge of data. My digital ocean server cannot enough space of disk to run, and thus, I bought and mounted one more volume but it is impossible to let the data to come to that volume. So the problem is what the config could I force the node to save the data at a place where I want, i.e. --datadir flag in geth.

Thanks you for reading, and most graceful from me if you could help me to get around.

**Comment by ngtuna** [comment]
@etienne-napoleone will help more. You can refer to this guide: https://medium.com/@prapatpolchan/how-to-add-volume-in-digitalocean-for-tomochain-masternode-by-step-a-to-z-b17363cbd8a5

**Comment by tphanson** [comment]
Oh perfect. Thank you so much.

**Comment by ngtuna** [comment]
You're welcome :-)
