### ISSUE TITLE
eth.getCandidateStatus improvement suggestion

### ISSUE THREAD

**Issue by pqv199x** [BuildOnViction/tomochain-v1#465]
- The current API is returning status for 1 coinbase. This could be a problem if the user wants to get statuses for more coinbases, the user will have to call API many times.

Suggestion: getCandidateStatus API receives an array of coinbase addresses as the first argument instead of a string of an address. Moreover, it would be easier for checking if the API returns epoch number in the response.

**Comment by thanhson1085** [comment]
Yep, seems a good suggestion.

But I think we should add more APIs like `eth.getCandidates` that will return list of candidate statuses and info. And still keep `eth.getCandidateStatus` to return status of a candidate

**Comment by thanhnguyennguyen** [comment]
Hi @pqv199x ,
Please check following example responses  and give your comments

 ```
eth.getCandidates(["0xb7e038b0229a97c9cb7ad798aa51757e1017a7d5","0xb7e038b0229a97c9cb7ad798aa51757e1017a7d4"], "0x2")
{
  candidates: {
    0xB7e038b0229A97c9CB7AD798aA51757E1017A7D4: {
      capacity: 50100,
      status: "MASTERNODE"
    },
    0xB7e038b0229a97C9cB7AD798aA51757e1017A7d5: {
      capacity: 50100,
      status: "PROPOSED"
    }
  },
  epoch: 2,
  success: true
}
```
```
eth.getCandidateStatus("0xb7e038b0229a97c9cb7ad798aa51757e1017a7d5", "0x2")
{
  capacity: 50100,
  epoch: 2,
  status: "PROPOSED",
  success: true
}
```

**Comment by thanhson1085** [comment]
I think `eth.getCandidate` should not require to input the candidate addresses. Then it should return all candidate status in the network

**Comment by pqv199x** [comment]
Implementation: https://github.com/tomochain/tomochain/pull/747
https://github.com/tomochain/tomochain/pull/748
