### ISSUE TITLE
Block time changes automatically

### ISSUE THREAD

**Issue by richardwing121** [BuildOnViction/tomochain-v1#469]
Block time changes from 1 second to 10 second automatically after 1500 blocks on private block chain

**Comment by ngtuna** [comment]
Not an issue. 10 sec timeout happens once one of the masternodes turns off.

**Comment by richardwing121** [comment]
kk thanks @ngtuna 
But if suppose there are four master node  and one of the master node turns off then the block time will increases or not ? As i am using three master node and block time increases when one of the master node turns off.
