### ISSUE TITLE
solidity go wrapper

### ISSUE THREAD

**Issue by benjiqq** [BuildOnViction/tomochain-v1#49]
I suggest to consider introducing naming convention for go-recompiled wrappers of solidity code separately, e.g.:

* blocksigner.sol (original Sol file)
* blocksigner.go (generated file from blocksigner.sol)
* blocksigners_wrapper.go (wrapper to access blocksigner.go)

**Comment by ngtuna** [comment]
Totally agree on the idea. That's also what we thought last week for having a separate go wrapper to interact with the go code generated from solidity. FWIW we introduce `contracts/utils.go`, which will be single entry point for all the interactions, in this PR #48

**Comment by ngtuna** [comment]
@benjyz I will close this issue. Feel free to reopen it for further suggestion from your side
