### ISSUE TITLE
Block sync failed after 1231200 blocks in private chain

### ISSUE THREAD

**Issue by richardwing121** [BuildOnViction/tomochain-v1#502]
WARN [04-23|17:20:54] Synchronisation failed, dropping peer    peer=04d2e1e0252392d9 err="retrieved hash chain is invalid"
INFO [04-23|17:20:54] Starting mining operation
INFO [04-23|17:20:54] Mining aborted due to sync
ERROR[04-23|17:20:54]
########## BAD BLOCK #########
Chain config: {ChainID: 1151 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: posv}

Number: 1231200
Hash: 0xe77454a3e39ee50854d42f7cc0399e5bd9a530af349c4cbcd91a8c2603e3f817

Error: invalid signer list on checkpoint block
##############################

WARN [04-23|17:20:54] Synchronisation failed, dropping peer    peer=379ec69d243b1b39 err="retrieved hash chain is invalid"
INFO [04-23|17:20:54] Starting mining operation
INFO [04-23|17:20:54] Mining aborted due to sync
ERROR[04-23|17:20:56]
########## BAD BLOCK #########
Chain config: {ChainID: 1212 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: posv}

Number: 1231200
Hash: 0xe77454a3e39ee50854d42f7cc0399e5bd9a530af349c4cbcd91a8c2603e3f817

Error: invalid signer list on checkpoint block
##############################

WARN [04-23|17:20:56] Synchronisation failed, dropping peer    peer=5f9d973c64853ffa err="retrieved hash chain is invalid"
INFO [04-23|17:20:56] Starting mining operation
INFO [04-23|17:20:57] Mining aborted due to sync
ERROR[04-23|17:20:58]
########## BAD BLOCK #########
Chain config: {ChainID: 1151 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: posv}

Number: 1231200
Hash: 0xe77454a3e39ee50854d42f7cc0399e5bd9a530af349c4cbcd91a8c2603e3f817

Error: invalid signer list on checkpoint block
##############################

WARN [04-23|17:20:58] Synchronisation failed, dropping peer    peer=b102c198b45ec7a6 err="retrieved hash chain is invalid"
INFO [04-23|17:20:58] Starting mining operation

**Comment by ngtuna** [comment]
Latest release fixed this issue https://github.com/tomochain/tomochain/releases/tag/v1.4.0

**Comment by parmarrushabh** [comment]
@ngtuna I have upgraded  my version to 1.4.0
Then also it shows me the same error whem i started my block from 1231200

**Comment by richardwing121** [comment]
@ngtuna i have upgraded the version to 1.4.0
The also it shows me the same error when i started my block from 1231200

**Comment by ngtuna** [comment]
@richardwing121 Okay. Show us more details on this log line: https://github.com/tomochain/tomochain/blob/master/consensus/posv/posv.go#L433

**Comment by richardwing121** [comment]
log.Error("Masternodes lists are different in checkpoint header and snapshot", "number", number, "masternodes_from_checkpoint_header", masternodesFromCheckpointHeader, "masternodes_in_snapshot", signers, "penList", penPenalties)
@ngtuna  this the line 433 of the code

**Comment by ngtuna** [comment]
@richardwing121 No. I meant can you show us that log in your running console to see further those information

**Comment by ngtuna** [comment]
I am closing this. Re-open it once you have more info. @richardwing121
