### ISSUE TITLE
eth & tomo namespace

### ISSUE THREAD

**Issue by benjiqq** [BuildOnViction/tomochain-v1#51]
what will be the strategy for ethereum & tomo namespace? for now things are merged in the core which I assume makes it not so easy to merge from ethereum/go-ethereum. IMO there is not much reason to merge much from go-ethereum except vetted bugfixes and on major releases. One would expect more big changes in tomo obviously.

**Comment by ngtuna** [comment]
@benjyz Tomo and Ethereum are eventually going in two different directions as we are running customized PoS with voting and they are rolling out Casper. Yes there is not much sense to keep things merged in the core components. Right now we are reorganizing the project (in a separate private repo) that we only import Ethereum's packages that we need. Hopefully we can publish it in next few months and start using it as mainstream repo.
