### ISSUE TITLE
Is there a guide to start mainnet without tmn?

### ISSUE THREAD

**Issue by lcgogo** [BuildOnViction/tomochain-v1#519]
I read the 
https://github.com/tomochain/tomochain/blob/master/README.md

However, the guide only cover testnet but not mainnet.

BTW: I do not want to use tmn to start mainnet. Because I want to store my data on a specific folder /data/tomo but not docker volume.

**Comment by ngtuna** [comment]
Follow this: https://docs.tomochain.com/masternode/create-tomochain-masternode/

**Comment by ngtuna** [comment]
Or you can follow the README with some network configuration (chainID, bootnodes) for mainnet described here: https://docs.tomochain.com/general/networks/#mainnet

**Comment by ngtuna** [comment]
a PR to update README is always welcome
