### ISSUE TITLE
Block got stuck !!!

### ISSUE THREAD

**Issue by richardwing121** [BuildOnViction/tomochain-v1#530]
Hello For testing I created 15 masternode with posv and proposed the masternode on the tomo master app but after certain time I lost my coin base address and 11 nodes are down and get slashed and all the nodes are stuck I can not see any block syncing any data on master node app And block also got stuck in the middle
How can I fix it? It would be great if you can provide any solution

**Comment by ngtuna** [comment]
Can you explain the coinbase address lost situation ?

**Comment by richardwing121** [comment]
unfortunately i forgot to take the back up of my coinbase address and some of my node went down and i deleted the node folder and some of that masternode got slashed from tomo master and all the nodes and master node are stuck and i can also not resign the slashed masternode!!

**Comment by ngtuna** [comment]
If nothing is changed, tomochain code run well with minimum of 3 online masternodes. If you lost coinbase private key, no chance to get the node back to work. If you want to resign the slashed node, login tomomaster using the owner account.

**Comment by richardwing121** [comment]
Yaa i have tried to resign the master node but i am unalble to resign the master node as blocks are stuck !!!
so i can not resign any master node

**Comment by ngtuna** [comment]
How many masternodes running now ? Restart masternode can help normally. Otherwise, your chain is stuck and the only option is re-run it from the start.

**Comment by richardwing121** [comment]
i have been running 15 master node from which 13 nodes are slashed and 2 nodes seems up
i can not understand properly are you telling me to re-run master node from block 0
is there any other way to start the master node and posv blockchain because as it has mined around 600000 blocks and it is stoped !!!

**Comment by ngtuna** [comment]
Okay now it's clear! Only 2 nodes online won't work. In this case, it's nothing you can do. You can't register new nodes as well as resigning old nodes as chain stopped. Restarting slashed masternodes doesn't help too as it can't create new block. So, the only option is re-run the chain from the start. I mean, destroy the network and recreate it. Sorry, it's the only option I can see.

**Comment by richardwing121** [comment]
KK thanks did it !!!!
Another question i have 15 master nodes on tomo master i have changed it from 150 to 10 masternode i can see 10 node as master node and rest of the 5 node on proposed and i read some article that round robin method is used to select master node per epoch and every epoch the node is selected by round robin method it has been around 90 epoch i have not seen round robin working till now and selecting nodes randomly doesn't work only rewards goes to 10 master node rest 5 doesn't have any rewards  .
The stake of all the nodes are same 50,000 tomo

**Comment by ngtuna** [comment]
- proposed nodes don't get reward.
- you should deploy TomoScan in order to see the round robin and randomization work. See `created by` and `verified by` info under a block detail page.

**Comment by richardwing121** [comment]
Hello @ngtuna as i was trying to understand the code for randamization from few days so i found at https://github.com/tomochain/tomochain/blob/master/common/constants.go 
There is var TIPRandomize = big.NewInt(3464000) on 27 line if i changes it to my current block and update my all node then randamization should work or not ?

**Comment by ngtuna** [comment]
Randomization works from the first day. That TIPRandomize is the block that we turned to use the new mechanism for randomization. But if you deploy tomochain from the beginning with latest code then yes you should change it.

**Comment by richardwing121** [comment]
@ngtuna where can i find the document or some information about new mechanism which was added after specific block number 
 ?
