### ISSUE TITLE
Remove takerfee, makerfee in a order

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#536]
TomoX will read the fee from smart contract and cache layer.
If relayer owner changes the fee, it does not effect immediately, but after checkpoint
We should discuss more about it.

**Comment by thanhnguyennguyen** [comment]
Got fee from relayer smartcontract : done in #637 
Removed makeFee, TakeFee in order: done in #630 
Closing this issue
