### ISSUE TITLE
Block get stuck on 0 in private blockchain

### ISSUE THREAD

**Issue by biuxmaster** [BuildOnViction/tomochain-v1#541]
Hi guys, I'm following the tomochain private testnet setup tutorial. I'm having an issue I started 3 nodes on this private network but it's stuck in "committing new block" I don't know what I'm doing wrong? can someone help me?

**Comment by ngtuna** [comment]
Great if you can show us some detail logs

**Comment by ngtuna** [comment]
close until getting feedback from @biuxmaster
