### ISSUE TITLE
BAD BLOCK error on running testnet full node.

### ISSUE THREAD

**Issue by KumanoTanaka** [BuildOnViction/tomochain-v1#563]
when I tried to run testnet node with `tomo` command, I faced the following error

```bash
ERROR[07-05|04:55:41] 
########## BAD BLOCK #########
Chain config: {ChainID: 89 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: posv}

Number: 1
Hash: 0xc186660e3cdd390cf4c7861ebc7ec358f0a5c258f0dec324c44581a3abdef90f


Error: invalid difficulty
##############################
```

as I discussed with Tomochain team, we found that in testnet we need `--tomo-testnet` on running daemon with `tomo` command.

for the people who will try like me, I will add some explanation on github readme.

**Comment by thanhson1085** [comment]
Thank you for your contribution.
