### ISSUE TITLE
the first 3-masternodes

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#60]
To simplify and speed up deployment, workflow (governance -> genesis block -> consensus). We decide run first 3 masters node with codebase address as below

```
0xf99805b536609cc03acbb2604dfac11e9e54a448
0x31b249fe6f267aa2396eb2dc36e9c79351d97ec5
0xfc5571921c6d3672e13b58ea23dea534f2b35fa0
```

And `owner` of the masternodes is `0x487d62d33467c4842c5e54eb370837e4e88bba0f`

2 addressed will hard-code in Validator Smart contract, and using in deployment script. So please take a look to this propose @ngtuna, @dinhln89, @etienne-napoleone

**Comment by etienne-napoleone** [comment]
Ok, I'll see about updating the genesis

**Comment by ngtuna** [comment]
It's all set. Good to close this issue now
