### ISSUE TITLE
Improve order pending process - OrderPool proposal

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#612]
Enhancement proposal:

- SDK updates `CreatedAt` into order before sending to TomoX
- TomoX stores order pending in a map (same as txs pool)
- M1 picks up X orders sorted by `CreatedAt` at once, then sorts by nonce before putting them into matching engine

**Comment by ngtuna** [comment]
Another approach is prioritized to make: implement OrderPool with the behavior as same as TxPool.

**Comment by thanhson1085** [comment]
Move to this issue: https://github.com/tomochain/tomochain/issues/742
