### ISSUE TITLE
RPC API - get Estimated ROI by staking for a candidate

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#620]
We should provide a RPC API to estimated ROI for staker who stake to a masternode

**Comment by anhntbk08** [comment]
@thanhson1085  Questions sir 
1. You want average ROI number or ROI of a specific staker?
2. Is there any case a staker staked into some master-nodes?

**Comment by thanhson1085** [comment]
Link to #658
