### ISSUE TITLE
Automatic integration test for TomoX

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#621]
- deploy Issuer, Listing, Relayer contract
- Deploy TRC21 (issue token, e.g ETH, BTC), apply tomoX (call Listing contract)
- Create a relayer (call Relayer contract)
- List tokens (ETH, BTC) on relayer (call Relayer Contract)
- Trades

**Comment by ngtuna** [comment]
close via #626
