### ISSUE TITLE
genesis block

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#63]
genesis block included TomoValidator Smart Contract and the first 3-masternodes
[https://gist.github.com/thanhson1085/fe1bd8511c9ef000ea9802321ef5d296](https://gist.github.com/thanhson1085/fe1bd8511c9ef000ea9802321ef5d296)

**Comment by thanhson1085** [comment]
link #64

**Comment by etienne-napoleone** [comment]
Is there any reason for using these pub keys in particular (for ex `94f99805b536609cc03acbb2604dfac11e9e54a448`)?

If they are hard coded, it means that masternodes in all envs will use the "same" (as same keys) account?

If yes, all envs will have a 3 masternodes base?

**Comment by thanhson1085** [comment]
yes, hard-coded coinbase of 3-masternodes. 

devnet, testnet will use this genesis.

genesis will be updated if Tomo Validator Smart contract changes. If updated, i will let us know.

**Comment by thanhson1085** [comment]
added randomize smart contract.

**Comment by etienne-napoleone** [comment]
Can we close this issue as the correct way to update the genesis would be a PR in https://github.com/tomochain/infrastructure ?

**Comment by thanhson1085** [comment]
yep, will close now.
