### ISSUE TITLE
send all rewards to deposit address / not coinbase

### ISSUE THREAD

**Issue by davidbowmankas** [BuildOnViction/tomochain-v1#647]
Long mentioned that at some point he would consider sending block /  all rewards to deposit address, not coinbase. since coinbase balance no longer displays in tomomaster, can that change be made? Thanks

**Comment by ngtuna** [comment]
Not sure I understand you correctly but currently block rewards are sent to owner address and txs fees are sent to coinbase. What did you recommend to change ?

**Comment by thanhson1085** [comment]
I think he suggest to send tx fee to MN owner address.
Actually, we already consider that. But this change will require hard fork.
I think add this issue to backlogs

**Comment by thanhson1085** [comment]
Move to #709
