### ISSUE TITLE
Remove takeFee, makeFee in order

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#648]
TomoX get the free from the smart contract

**Comment by thanhnguyennguyen** [comment]
fix in https://github.com/tomochain/tomochain/pull/637

The rest thing we need to do: remove these fields out of signature
https://github.com/tomochain/tomochain/blob/tomoX/tomox/validator.go#L116

**Comment by thanhnguyennguyen** [comment]
Remove makeFee, takeFee from signature will be done in https://github.com/tomochain/tomochain/pull/630

https://github.com/tomochain/tomochain/pull/630/files#diff-64abae97e2ffcc08f9b73a74b0dcb83bL116

**Comment by thanhnguyennguyen** [comment]
Got fee from relayer smartcontract : done in #637 
Removed makeFee, TakeFee in order: done in #630 
Closing this issue
