### ISSUE TITLE
Add params --tomox.mongodb.name --tomox.mongodb.url

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#677]
Currently, we hard-code the value at:
https://github.com/tomochain/tomochain/blob/ef51d97af0f58ef566beae958fe9d34bfe19a6c1/tomox/mongodb.go#L35

So we should add more params for `tomo` command to custom the value.
`--tomox.mongodb.name`  default value `tomodex`
`--tomox.mongodb.url` default value `mongodb://localhost:27017`

**Comment by thanhnguyennguyen** [comment]
close as merging #687
