### ISSUE TITLE
Should be returning better error log

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#71]
```
INFO [07-03|07:53:28] Successfully sealed new block            number=1 hash=809715…44759d
INFO [07-03|07:53:28] 🔨 mined potential block                  number=1 hash=809715…44759d
INFO [07-03|07:53:28] Debugging info                           number of masternodes=3 previous=0xf99805B536609cC03AcBB2604dFaC11E9E54a448 position=0 current=0xf99805B536609cC03AcBB2604dFaC11E9E54a448 position=0
INFO [07-03|07:53:28] Not our turn to commit block. Wait for next time 
0 - 0xf99805B536609cC03AcBB2604dFaC11E9E54a448
1 - 0x31b249fE6F267aa2396Eb2DC36E9c79351d97Ec5
2 - 0xfC5571921c6d3672e13B58EA23DEA534f2b35fA0
WARN [07-03|07:53:30] Discarded bad propagated block           number=1 hash=20a319…f0da57
ERROR[07-03|07:53:30] Fail to get snapshot for sign tx validator. 
WARN [07-03|07:53:31] Discarded bad propagated block           number=1 hash=160123…592821
ERROR[07-03|07:53:31] Fail to get snapshot for sign tx validator. 
WARN [07-03|07:53:39] Discarded bad propagated block           number=2 hash=484fa2…e65033
ERROR[07-03|07:53:39] Fail to get snapshot for sign tx validator. 
```

https://github.com/tomochain/tomochain/blob/master/eth/backend.go#L197

@dinhln89 please return err parameter then we can have better understanding on what happened

**Comment by etienne-napoleone** [comment]
To give a little more context, this happened in a 3 masternodes setup.
Those logs comes from the first node who start and who's used as bootnode by the other two.
It happens quite quickly after the first block is mined.
Using https://github.com/ngtuna/tomochain/tree/voting-smc

**Comment by ngtuna** [comment]
Ther PR was merged so you can reproduce this issue on master branch

**Comment by etienne-napoleone** [comment]
@nguyenbatam please reference the PR or commit you made to solve this issue before closing

**Comment by ngtuna** [comment]
@etienne-napoleone https://github.com/tomochain/tomochain/pull/68/files#diff-e42690942282286ede9e53bbe7b0c248R199

Sorry for some missing bits
