### ISSUE TITLE
Cache tradingfee by epoch

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#713]
Currently, when process txmatch, we read trading fee from the state (smart contact)
Issue: low performance, relayer owner can change trading frequently

To optimized it, we should cache trading fee by epoch.
So the flow will be:
- get current epoch number
- query trading fee by epoch number, if nil, read from state, store to cache by epoch number key

**Comment by thanhnguyennguyen** [comment]
please help to cache valid relayer list by epoch as well

**Comment by thanhson1085** [comment]
The fee is validated in Relayer Smart Contract. We do not need to cache it
