### ISSUE TITLE
Error handling on verification funcs

### ISSUE THREAD

**Issue by ngtuna** [BuildOnViction/tomochain-v1#719]
Should be carefully handling errors on verification funcs to make chain keep running instead of throwing out bad block error and making chain stuck. For example:

`validateMatchingOrder` causes bad block in case Relayer Address is invalid which can be easily made by sending fake order via RPC API.

**Comment by thanhnguyennguyen** [comment]
avoid this by validating orders before pushing to order pool: #736 #741

**Comment by thanhnguyennguyen** [comment]
fixed in #736 #741
