### ISSUE TITLE
Update final Relayer Smart contract

### ISSUE THREAD

**Issue by thanhnguyennguyen** [BuildOnViction/tomochain-v1#746]
Due to the change by @vutran1710   in https://github.com/tomochain/tomorelayer/blob/master/contracts/Registration.sol#L17

Update this function 
https://github.com/tomochain/tomochain/blob/tomoX/tomox/relayer_state.go#L27

**Comment by thanhson1085** [comment]
Final contract: https://github.com/tomochain/tomorelayer/blob/master/contracts/Registration.sol
