### ISSUE TITLE
Discuss to add a method to check block status (signers, finality)

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#79]
With POSV consensus, we should enable to check block status to who the values below:
- How many masternodes signed the block
- Finality or not yet?

For implements, i suggest 2 options:
- Check block status by using `eth.getBlock('latest')` command. 
- Implement a new command, e.g. `eth.getBlockStatus('latest')`

**Comment by thanhson1085** [comment]
We need have more 2 properties:
`signers: arrays of signers`
`finality: true/false`

**Comment by dinhln89** [comment]
https://github.com/tomochain/tomochain/pull/113

Please check at this PR. Thanks!
