### ISSUE TITLE
versioning and tagging

### ISSUE THREAD

**Issue by benjiqq** [BuildOnViction/tomochain-v1#84]
tags have been removed. for reference the first commit 28/3/2018: c3fbc2401281338637d11102829ecdf7ae742697
https://github.com/tomochain/tomochain/commit/c3fbc2401281338637d11102829ecdf7ae742697

last commit of eth from 28/3/2018:  a095b84ec5a35cb3432380cc677d4e244b4a137f
https://github.com/tomochain/tomochain/commit/a095b84ec5a35cb3432380cc677d4e244b4a137f

tag v.1.8.2 is from 5/3/2018

**Comment by ngtuna** [comment]
At some places in the source code there is still geth v1.8.2 appears. That would be great to clean a bit and restart versioning as we are going to release the first (alpha) version of tomo cc/ @nguyenbatam

**Comment by ngtuna** [comment]
closed via #100
